###
GET http://localhost:8080/login/



###
GET http://localhost:8080/test/auth1
x-token: 6qEDA9xXx5bMPXYU92r98vrLoEnTtGHcOQ6lYAEs37kAutnixnVQl1WsofueRMAF



###
POST http://localhost:8090/login/
Content-Type: application/json

{
  "name": "lc",
  "pwd": "123456"
}


###
GET http://localhost:8090/personal/info
x-token: AYoTl7qoVOr201oc1wGDhpc1FNgFnQUAdOwloeG3JroVtkAOYZpSBzOUbk5A4t8QRfAYEk3xjKtVoEBPHc6MvA==

